apiVersion: v1
kind: BuildConfig
metadata:
  name: lsteck.test-155-typescript
  labels:
    app: test-155-typescript
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/lsteck/test-155-typescript.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: lsteck2-dev
        - name: BRANCH
          value: master
